Repository GSG-G10/HijabFashion, pull requests merged in 2021-07, with the labels that each got.

#17 File structure
  .gitignore
  Js/main.js
  Js/test.js
  assets/css/style.css
  index.html
  package-lock.json
  package.json
  seller.html
Labels: Awaiting Review

#19 edit file strucure
  css/style.css
  html/seller.html
Labels: Awaiting Review

#21 add images
  assets/images/1.jpg
  assets/images/2.jpg
  assets/images/3.jpg
  assets/images/4.jpg
Labels: Awaiting Review

#23 add defalut data items #22
  Js/data.js
Labels: Awaiting Review

#24 create cart page
  css/cart.css
  html/cart.html
Labels: Awaiting Review

#25 16 create html for index page
  assets/images/search_icon.png
  css/style.css
  index.html
Labels: Awaiting Review

#27 search by name func with test
  Js/data.js
  Js/dom.js
  Js/main.js
  Js/test.js
  index.html
  package.json
Labels: Awaiting Review

#30 set style and structure for seller page #29
  css/seller.css
  html/seller.html
  package.json
Labels: Awaiting Review

#28 display item for customer #10
  Js/data.js
  Js/main.js
  css/style.css
  index.html
  package-lock.json
  package.json
Labels: Awaiting Review

#31 9 filter by category
  Js/dom.js
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#26 4 add to cart
  Js/cart.js
  Js/main.js
Labels: Done

#33 set function for seller products #12
  Js/data.js
  Js/dom.js
  Js/main.js
  Js/seller-dom.js
  Js/test.js
  css/seller.css
  css/style.css
  html/seller.html
  index.html
Labels: Awaiting Review

#32 3 filter items by price for customer
  Js/data.js
  Js/main.js
  Js/test.js
  package-lock.json
Labels: Awaiting Review

#37 edit tests description
  Js/cart.js
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#35 create the popup window
  css/seller.css
  html/seller.html
Labels: Awaiting Review

#38 create total price calculation test and function
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#40 edit filterByCategory spelling
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#41 write the add new product test and function
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#42 delete product as seller
  Js/cart.js
  Js/main.js
Labels: Awaiting Review

#44 add logic file
  Js/logic.js
  Js/main.js
  Js/test.js
Labels: Awaiting Review

#47 write read me #2
  README.md
Labels: In-Progress

#48 add listener
  Js/cart.js
  Js/data.js
  Js/dom.js
  Js/main.js
  Js/seller-dom.js
  css/style.css
  html/cart.html
  html/seller.html
  index.html
Labels: Awaiting Review

#53 Update README.md
  README.md
Labels: Done

#55 Update README.md
  README.md
Labels: Done
